[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.4"

[[constraint]]
  branch = "master"
  name = "github.com/swaggo/echo-swagger"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true
